FROM prom/prometheus:v2.48.0

USER root

COPY config/prometheus.yml /etc/prometheus/prometheus.yml

RUN chown -R nobody:nobody /etc/prometheus /prometheus

USER nobody

EXPOSE 9090

CMD ["--config.file=/etc/prometheus/prometheus.yml", \
     "--storage.tsdb.path=/prometheus", \
     "--web.console.libraries=/usr/share/prometheus/console_libraries", \
     "--web.console.templates=/usr/share/prometheus/consoles", \
     "--web.enable-lifecycle"]
