FROM grafana/grafana:10.2.2

USER root

COPY config/grafana/datasources.yml /etc/grafana/provisioning/datasources/datasources.yml

RUN chown -R grafana:grafana /etc/grafana /var/lib/grafana

USER grafana

EXPOSE 3000
