FROM haproxy:2.8-alpine

RUN addgroup -g 1000 haproxy-user && \
    adduser -D -u 1000 -G haproxy-user haproxy-user

COPY config/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

RUN chown -R haproxy-user:haproxy-user /usr/local/etc/haproxy

USER 1000

EXPOSE 80 443 8404

CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
